### ISSUE TITLE
Pouvoir s'identifier

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#1]
En tant qu'étudiant à distance, 
Je souhaite pouvoir m'authentifier
Afin de pouvoir acceder au contenu de cours
Ainsi qu'au exercices

**Comment by yaf** [comment]
Sur ce coup là, j'aimerais suggerer un truc un peu amusant, donc pas d'emballement sur la real avec du devise. 

J'aimerais que l'on puisse faire du log avec email only (pas de mot de passe).
Je vous donnerais le détail plus tard je crois.

**Comment by Em-AK** [comment]
OK comme vu hier, dans un premier temps l'utilisateur rentre juste son email pour être authentifié. (pas secure du tout mais on verra plus tard avec personna ou tabouille custom avec les cookies)
