### ISSUE TITLE
Touver un nouveau nom officiel pour cette app

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#10]
Pour communiquer un de ces jours sur le fait que notre plateforme de formation à distance est sous licence libre,
- il serait bien d'avoir un nouveau nom un peu plus cool
- trouver la licence qui nous conviens

**Comment by yaf** [comment]
Ah ? C'est close ? C'est quoi le nouveau nom ? 

Je me permet de re-ouvrir.

**Comment by jum-s** [comment]
Ah bah je pensais que simplonline était acquis.  Au temps pour moi
Le 13 sept. 2014 14:09, "Yannick François" notifications@github.com a
écrit :

**Comment by yaf** [comment]
Simplonline est le nom de notre "offre" de formation ouverte à distance. Mais cette application ne dois pas forcement porter ce nom la, histoire de permettre à qui veux de l'utiliser pourquoi pas ?

Mais tu as raison, je crois que c'est un sujet pour plus tard... beaucoup plus tard. Je vais renomer le projet et clore cette discussion. :-)
