### ISSUE TITLE
Virer carrierwave

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#13]
virer carrierwave pour stoker le contenu des fichiers d'essais dans la bdd

_repris de la liste TODO du fichier README_

**Comment by jum-s** [comment]
Pas sur que cela soit très secure d'inscrire le contenu du fichier en string dans la BDD. Qu'en pensez-vous ?

**Comment by yaf** [comment]
C'est pas forcement un soucis de sécurité.  C'est plutôt un coté pratique de tout avoir dans la base, et on backup la base et tout est là versus il faut backup la base ET les fichiers. C'est un soucis de production. 

N'ayant rien tranché là dessus pour le moment on peut attendre un peu.

**Comment by jum-s** [comment]
Finalement il fait partie intégrante de l'application
