### ISSUE TITLE
Timestamp presence

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#19]
En Tant qu'administateur et organisateur des cours
Avoir une trace de chaque requête par utilisateur (date/heure utilisateur et lien)
Afin de pouvoir justifier de la participation de chaque utilisateur pour le DIF ou autres.

**Comment by jum-s** [comment]
Les notifications Rails suffiraient ? Ca vaut le coup que je m'y penche un peu ?
http://api.rubyonrails.org/classes/ActiveSupport/Notifications.html

**Comment by yaf** [comment]
Pas forcement très pressé.

Je n'ait peut-être pas bien compris les notif rails, mais ce qu'il faudrait c'est juste une trace dans une base de données (vu les gros volume attendu il faut peut-être mettre ça dans un mongodb ?). En attendant on peut le mettre dans une table interne.

Mais surtout, on peux attendre un peu, c'est à avoir pour le 6 octobre.

**Comment by yaf** [comment]
Bon, je viens de regarder les notifications. c'est pas mal. Peut-être un peu trop, mais nous n'avons plus trop le luxe de tester un autre truc.

A voir maintenant où nous voulons stocker ces infos (il devrait y en avoir beaucoup !)

**Comment by yaf** [comment]
Solution temporaire car je pense que nous allons manquer de place: une table log avec des champs timestamps, et un trace dans lequel on sérialize en json...

Je pense que ça va finir dans un mongo quelque part tout ça....
