### ISSUE TITLE
Lexique

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#21]
En tant qu'élèves présent
Je repertorie les mots importants dans un lexique
Afin de les expliquer et permettre une regroupement de définition

En tant qu'élèves distant
Je peux accéder à un lexique
Afin de voir une liste de mots clé

En tant qu'élèves distant
Dans un chapitre, si un mot est un peu technique ou complique, je peux cliquer dessus
Afin d'en voir une définition.

**Comment by jum-s** [comment]
En tant qu'utilisateur 
je peux voir quel est l'auteur d'une description dans le lexique
je peux voter pour la meilleure description

**Comment by jum-s** [comment]
Pour afficher les liens vers le lexique dans une lesson on fait ça en Javascript après le chargement de la page? Ou dans le controller ?

**Comment by yaf** [comment]
Je crois que le mieux sera dans le model lexique et dans le model chapitre. Au moment d'enregistrer, parcourir le texte/contenu pour mettre un lien vers le lexique quand on trouve un mot du lexique, et inversement, quand on ajoute un mot, on parcour les contenus pour mettre des liens.

Ces opérations pouvant prendre du temps, soit c'est un bot qui passe toutes les heures, soit au moment d'ajouter un mot ou du contenu, on pose une demande d'analyse dans un sidekiq pour que le job soit fait en off/asyncrhone.

Dans notre cas le truc se ferais sur le serveur distant, mais bon, ce n'est peut-être pas grave ?
