### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#28]
En tant que présentiel
Je met un tag sur mon contenu
afin de pouvoir oganiser mes lectures et les type de travaux

**Comment by jum-s** [comment]
"mon contenu" c'est Chapter et Définitions ?
Les tags apposés seront différents entre utilisateurs sur un contenu similaire ?

Pour spécifier un peu les types de travaux on pourrait ajouter une entrée "catégorie" dans le modèle Tag (pour associer des couleurs en front et suggérer des tags déjà émis lorsqu'on veut taguer un contenu)

On pourrait lier Tag et Définitions aussi, mais ca c'est pour plus tard

**Comment by yaf** [comment]
Just echapter (définitions c'est pour le goupe complet, pas besoin d'auteur dessus.

Evitons le coté figé des catégories. Les tags pourrais être fix. La diff entre tag et catégorie de mon point de vue c'est que nous pouvons avoir plusieurs tag :-) Seul les présentiel pourrait créer un tag.

**Comment by jum-s** [comment]
Donc juste chapter, mais meme tags pour tout le monde sur un chapter, ou chacun peut mettre ses propres tags comme il a compris le chapter?
Si un tag correspond à un keyword de definition alors je peux cliquer dessus pour accéder à la définition ?

**Comment by yaf** [comment]
Non, en fait on va faire une sorte de mixte entre catégorie et tag. En fait c'est des multiple catégorie, tout simplement. Je vais les définir d'ailleurs, pas besoin d'interface, pour le moment, pour les créer, les suppriner ou autres. Il faut juste pouvoir les ajouter sur les chapitres (0 à n par chapitre)
