### ISSUE TITLE
Suppression de définition

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#30]
En tant qu'élève présent
Je peux supprimer une définition
afin de pouvoir nettoyer le lexique si une définition ne sert plus à rien

Attention à penser à supprimer les liens qui aurait pu être crée vers cette définition.

**Comment by Em-AK** [comment]
La définition est supprimée, pas encore le lien. Je scrute pour trouver d'où ça viens.

**Comment by Em-AK** [comment]
Résolu dans 4db9156b28993e40fffc41622268b872351c39fa

**Comment by yaf** [comment]
Je viens de faire un essai:

Création d'un contenu dans un chapitre avec le mot truc dedans (juste une phrase).
Création d'un mot clé dans le lexique
Quand je reviens sur le chapitre, pas de lien sur le mot truc pour aller voir la définition.

Je n'ai pas tester la suppression du coup.

**Comment by Em-AK** [comment]
Je n'arrive pas à reproduire ton erreur.  
En suivant pas à pas ton cheminement j'ai un lien dans mon chapitre.

**Comment by yaf** [comment]
Ok, avec chose ça fonctionne. Je n'étais peut-être pas à jour en source.
