### ISSUE TITLE
fr.yml -> faute

### ISSUE THREAD

**Issue by londusboub972** [simplonco/simplonline#41]
line138
 placeholder:
    content: "ex; Un avis, une questions"

must be :
 placeholder:
    content: "exemple: Un avis, une question"

Title in /messages 
 'Nous avons découvert cette semaine... '
This can be better :
Titre du Message ou Question ?

**Comment by yaf** [comment]
Non pour le dernier point. L'idée d'un place holder est de donner un exemple d'utilisation. C'est au label de préciser ce qui doit être dedans :-)
