### ISSUE TITLE
Coloration syntaxique

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#44]
Dans le contenu des chapitre, le code n'est pas coloré.

**Comment by jum-s** [comment]
le code doit etre d'une même couleur (genre gris foncé) ou coloré come dans une éditeur ?
Dans le deuxième cas c'est un travail de fourmi non ? (https://github.com/fazibear/colorize)

**Comment by yaf** [comment]
Il y a des gems pour ça... surement

**Comment by jum-s** [comment]
justement, a part le fameux colorize (en lien au dessus), j'ai rien trouvé
