### ISSUE TITLE
Css 

### ISSUE THREAD

**Issue by londusboub972** [simplonco/simplonline#46]
Font size des titres à revoir.

**Comment by yaf** [comment]
Pourquoi ? Explication ? Trop petit ? Trop gros ?

Merci de donner un peu de détail dans les déclaration de bug :-)

**Comment by londusboub972** [comment]
Les h1 h2 h3 ne sont pas respectés, du coup la mise en page des leçons ne se fait pas correctement

**Comment by yaf** [comment]
respecté ? ça signifie quoi ? Il n'y à pas les balises ?

**Comment by londusboub972** [comment]
Les h1 h2 h3 sont confondus.
