### ISSUE TITLE
Scroll Panic?

### ISSUE THREAD

**Issue by londusboub972** [simplonco/simplonline#51]
Can't explain that, got a scroll and load panic on dashboard.

**Comment by jum-s** [comment]
Est tu sur que ça vient de l'application? A vérifier
Penses tu que ça puisse arriver sur toute les machines ou juste sur ta
configuration?

**Comment by londusboub972** [comment]
Justement j'ai vérifié ça avec un simplonien, et du coup il à eu aussi ce bug, mais en effet je vais vérifier si c'est pas le navigateur.
