### ISSUE TITLE
test d'un QCM 

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#53]
En tant que staff ou présentiel
Je peux faire le qcm comme si j'étais un distant
Afin de pouvoir me rendre compte du rendu de mon travail.

Peut-être faut-il dupliquer les boutons de création et mise à jour d'un qcm

**Comment by jum-s** [comment]
On s'en fout de créer des qcm "test" dans la base?
Un bot pourrait supprimer régulièrement les answer créé par les user
presentiel.
 Le 3 oct. 2014 13:21, "Yannick François" notifications@github.com a
écrit :

**Comment by yaf** [comment]
Ça ne fonctionne pas vraiment. (ou alors j'ai un loupé)
