### ISSUE TITLE
Test EDX

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#6]
Je me rend compte que nous n'avons même pas laisser une change à une plateforme existante.

Pourriez vous tester edx au moins, et me faire un retour sur l'usage en tant qu'élève exterieur (je suis des cours je fais mes exo), et élève intérieur (je cré les cours et je cré les exos).

Merci :-)

**Comment by jum-s** [comment]
On avait regardé ensemble avec émilien en mai déjà. Ça ne nous avait pas
semblé très adaptable comme format (vidéos + qcm) c'est aussi pour ça qu'on
a suggérer de partir de scratch
Le 31 juil. 2014 10:25, "Yannick François" notifications@github.com a
écrit :

**Comment by yaf** [comment]
J'ai l'impression qu'il y a des outils/plugins qui permettrais de le faire XQueue, XBlock, CodeJail...

C'est sur que si on arrive à faire tourner un truc tranquillement, ce n'est peut-être pas nécessaire... Mais la question est importante: Faut-il faire un truc dans notre coin et donc nous pouvons rester très spécifique et faire quelque chose qui colle vraiment à notre besoin ou bien essayer d'utiliser et participer aux outils existant, quitte à passer plus de temps pour faire en sorte qu'ils répondent à notre besoin ?

**Comment by yaf** [comment]
Frédéric Bardeau à dit:

mon avis, car non technique, n'est peut être pas important mais EDX c'est une super plateforme qui fait autorité dans le monde entier, un projet opensource avec une vraie communauté et on a même des intégrateurs EDX (neopedia) qui nous proposent leur aide pour la customiser, en terme de communication en plus c'est bien

JDCJDR

**Comment by yaf** [comment]
Bon, je clos cela pour l'instant.
