### ISSUE TITLE
Petit problème de chapitre dans [S01] The beginning

### ISSUE THREAD

**Issue by ghost** [simplonco/simplonline#67]
Salut, (j'espère ne pas générer trop de taf à l'équipe je sais que tout le monde est dans les starting block, j'attends moi même 18h avec impatience)

A chaque fin de page de la Lesson 1 lorsque l'on clique sur le bouton "Chapitre suivant" nous sommes redirigé vers la page http://foad.simplon.co/lessons/1/chapters/23 et ca peut importe sur quelle page nous étions.
C'est vraiment pas urgent, il est possible de revenir à http://foad.simplon.co/lessons/1 et de choisir le chapitre suivant :)
Donc pas de stress.

Merci

**Comment by lisasugiyama** [comment]
Bonsoir et bravo !

1) Même remarque sur le problème de liens "suivant". La navigation n'est pas fluide entre les chapitres....
Apparemment en cours de correction à l'heure où j'écris ce commentaire :+1: 
Rajouter un bouton précédent aussi (?)

2) Il y a également d'autres liens qui amènent nulle part ou qui amènent vers une page 404.
cf. les liens des sources

3) Les liens vers les définitions ne sont pas toujours pertinents. 
Ex. pour la définition "OS" on a < comp**os**ant > qui est souligné et qui renvoit vers la définition "OS".

Merci pour les corrections et à bientôt :)

**Comment by yaf** [comment]
Bonjour,

Merci pour vos remonté d'erreurs. Je crois que la plupart son corrigé maintenant.

Pour les éventuelle prochaine fois, pourriez vous les noté dans des fiches séparé quand il s'agit de sujet différent biensur :-)

Merci encore.

**Comment by lisasugiyama** [comment]
Bonjour et merci pour les correctifs !

Effectivement, je m'en suis aperçu après avoir posté le commentaire.
Oui, bien sûr pour d'éventuelles prochaines fois, je mettrais les bugs dans des fiches séparées :)

À bientôt 

Lisa
