### ISSUE TITLE
Liens manquant (ou brisé)

### ISSUE THREAD

**Issue by ghost** [simplonco/simplonline#68]
Dans la page 10 "S'essayer à la lecture du code"
http://foad.simplon.co/lessons/1/chapters/10

Le lien github qui semble être un exemple de code en Ruby ne fonctionnement pas :(

https://github.com/huffp[os](/definitions/8)tdata/fech-search/blob/master/lib/fech-search/search.rb

Merci (promis j'arrête)

**Comment by Em-AK** [comment]
Directement lié à la regex qui ajoute les liens vers le lexique dans le corps des chapitres.
La regex substitue aussi le contenu des liens. Ici `os` par `[os](definitions/8)`
Je vois que Yannick a commencé à traiter le problème ici b83416ab52e013f5a4eaa1b4b572266189ac639e

**Comment by yaf** [comment]
Je vais supprimer les liens
