### ISSUE TITLE
Lien dans une nouvelle fenêtre ?

### ISSUE THREAD

**Issue by sibor94** [simplonco/simplonline#69]
C'est un tout petit détail mais serait-il possible de changer la cible des liens dans les textes en target="_blank" pour pouvoir consulter la page dans un nouvel onglet ?

**Comment by yaf** [comment]
Et bien ce n'est pas vraiment une bonne pratique. C'est à vous d'utiliser le click du milleu, ou le control+click pour ouvrir dans un nouvel onglet. Il me semble même que vous pourriez configurer votre navigateur pour le faire.

http://climbtothestars.org/archives/2002/12/30/abandonnez-target_blank/

:-)
