### ISSUE TITLE
QCM

### ISSUE THREAD

**Issue by jum-s** [simplonco/simplonline#7]
En tant qu'élève présentiel
Je peux des créer des QCM a partir d'un formulaire sur l'app ou bien d'un fichier JSON brut
Afin de permettre aux formés à distance de répondre dans un format type memrise aux questions posées (question répondue une par une, avec explications si réponse fausse)

**Comment by jum-s** [comment]
On a discuté 20 min de ca, qu'en penses-tu, project owner ?

**Comment by yaf** [comment]
Je le reformule pour le style:

En tant qu'élève présentiel
Je  crée un QCM
Afin de permettre aux formés à distance de répondre à des questions

:-)

Le reste et un détail d'implémentation nous allons dire.

**Comment by yaf** [comment]
Vérifier et corrigé.
Le partie pris de dire que nous pouvons faire et refaire le qcm est intéressant. Mais du coup on ne stock aucune donnée sur le sujet. A voir si nous n'aurons pas besoin de l'améliorer.
