### ISSUE TITLE
Glossaire : éviter que le moteur reconnaisse des entrées au beau milieu des articles

### ISSUE THREAD

**Issue by fflakito** [simplonco/simplonline#82]
Que diriez-vous de changer les entrées du glossaire de la FOAD en remplaçant, par exemple, l'entrée OS par [OS] ?
Bénéfice : on n'aurait plus le moteur du site qui remplacerait toutes les occurences -os- par le lien tout moche. Pour le moment, quand on marque "dossier" ça remplace automatiquement par "d[OS]sier"...

Par contre, on aurait toujours moyen d'appeler facilement le lien en mettant le terme entre crochets, quand on le souhaitera.

**Comment by yaf** [comment]
En fait le moteur de remplacement est déjà coupé. Par contre je n'ai pas nettoyé les textes déjà transformé.

Le hic de la solution qui avait été mise en place c'est quelle est intrusive => Elle modifiait le texte existant pour y ajouter des liens. Je pense que nous pourrions le faire en javascript (je crois que c'était l'idée original de @jum-s ) Cela permettrais de ne faire des liens que sur la première occurence du mot et de le faire de manière non intrusive.

Ça vous conviendrais ?

**Comment by fflakito** [comment]
Qu'entends-tu par "non intrusif" ? Ca le fait de manière automatique ou pas ?
L'autre partie assez rapide ce serait de corriger le CSS pour rendre les liens un peu moins visibles (là ils sont bien, bien gros). Ca mérite peut-être un autre "issues", étant donné que l'apparence du site dans son ensemble pourrait être améliorée ?

**Comment by yaf** [comment]
Non intrusif ça signifie que le lien pourrais être ajouter en javascript dansla page et non dans le texte original stocké en base de donnée
