### ISSUE TITLE
Suppression message forum

### ISSUE THREAD

**Issue by londusboub972** [simplonco/simplonline#84]
Des messages du forum sont effacés...

**Comment by yaf** [comment]
Effacé ? Par des personnes qui ont éffacé leurs message ? Ou bien c'est juste pas afficher ?

**Comment by londusboub972** [comment]
Pas affiché

**Comment by yaf** [comment]
Est-ce que maintenant ça fonctionne ?

**Comment by londusboub972** [comment]
Oui.
Le 12 oct. 2014 12:04, "Yannick François" notifications@github.com a
écrit :
