### ISSUE TITLE
Bug dans le code inséré (dans la lecon)

### ISSUE THREAD

**Issue by londusboub972** [simplonco/simplonline#87]
https://www.filepicker.io/api/file/ozisL8SQQKauaCfoe1Bs

http://foad.simplon.co/lessons/2/chapters/17

/\* On supp
[ os ]](/definitions/8)e qu'il le ferme*/  
Mise en forme sur le github, car sinon reconnus en markdown

**Comment by yaf** [comment]
Done,

Pareil, tu aurais pu corriger direct.

**Comment by londusboub972** [comment]
Was busy at the moment.

2014-10-13 22:24 GMT+02:00 Yannick François notifications@github.com:
