### ISSUE TITLE
Forum complet ?

### ISSUE THREAD

**Issue by fflakito** [simplonco/simplonline#89]
Serait-il possible de profiter de **modules déjà développés** pour importer d'un coup pas mal de fonctionnalités qui nous seraient utiles ? Je pense notamment à : 
- ce serait bien de rassembler les réponses aux messages en fil sous le message et pas en nouveau message car du coup c'est compliqué de suivre.
- présentation du forum par topics (et pas par messages)
- suivi de topics 
- un lien pour chaque post

**Comment by yaf** [comment]
Ça va avec ça ?

"Hello, Ce serait bien de rassembler les réponses aux messages en fil sous le message et pas en nouveau message car du coup c'est compliqué de suivre.

Feature de ouf !"

http://foad.simplon.co/messages/194

**Comment by giniouxe** [comment]
FrenchFlakito, ça te va ?

**Comment by fflakito** [comment]
Yes, c'est ça !

**Comment by giniouxe** [comment]
Merci. Je regroupe les deux.

**Comment by yaf** [comment]
Je peux regarder discourse, mais du coup on peut se poser la question de la pertinance de la plateforme... Faut-il continuer à la développer ?

**Comment by giniouxe** [comment]
discourse ?

**Comment by yaf** [comment]
http://www.discourse.org/ Pardon :-)

**Comment by giniouxe** [comment]
Intéressant mais j'ai une petite inquiétude : 

" Discourse is a JavaScript application designed for the next 10 years of the Internet, so the minimum web browser requirements are high:
    Internet Explorer 10+
    Google Chrome 24+
    Firefox 14+
    Safari 5.1+
We do officially support Internet Explorer 9, but some functionality will be unavoidably broken. "

**Comment by yaf** [comment]
Bien vue ! 

Voici une raison de faire nous même :-p Mais y'a du taf.

**Comment by giniouxe** [comment]
Où est passée fainéantise du développeur averti ?

**Comment by fflakito** [comment]
Je ne sais pas si ce point doit être rédhibitoire, si Discourse semble être adapté par ailleurs ?
En tout cas, sur Facebook la demande pour un forum en bonne et due forme croît.

Zut, j'ai fermé le sujet par erreur ! Yannick, si tu sais comment rouvrir... -_-' Désolé
