### ISSUE TITLE
Connexion Localhost

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#9]
Comment faire la partie connexion quand on est en localhost avec Personna ?

**Comment by yaf** [comment]
Finalement ça  à fonctionné en localhost, connecté, mais la question reste valide, je la reformule:

Comment faire tourner l'app en mode dev offline ?

**Comment by Em-AK** [comment]
C'est une très bonne question !
La [gem que j'utilise pour Personna](https://github.com/intridea/omniauth-browserid) est basée sur Omniauth.
Du coup je vais [creuser par ici](https://github.com/intridea/omniauth/wiki/Integration-Testing) pour comprendre comment faire.

**Comment by yaf** [comment]
Il y a surement un truc autour de ces lignes https://github.com/simplonco/sensei/blob/master/app/controllers/sessions_controller.rb#L3 et de la configuration de omniauth. Je vais regarder aussi.

**Comment by yaf** [comment]
Je me demande dans quelle mesure nous ne pourrions pas avoir un formulaire dans lequel les personnes saisissent une adresse email, puis, si nous sommes en prod, nous appelons persona, sinon, en fonction de l'email (prédéfini) nous pouvons orienté soit un user type à distance ou bien en présentiel...

Je vais regarder si persona peut fonctionner sans la popup et le JS

**Comment by yaf** [comment]
Bon, pas de persona sans JS... peut-être que nous allons faire un grand classique, user/password... car j'ai l'impression que rien ne nous permettra en development de faire en sorte de s'authentifier soit en présentiel, soit en distant. Le seul truc que je lis c'est à propos de "mock" le login en test...

**Comment by yaf** [comment]
Remplacement fait dans le commit 16f52a1e12ce47bd8ccbbc79f97d34349672cfaf Je ferme ce ticket.
