### ISSUE TITLE
Impossible d'ajouter un player vidéo

### ISSUE THREAD

**Issue by benoittgt** [simplonco/simplonline#91]
En tant que présentiel je voudrais insérer un player video.

Exemple de code : 

``` html
<video id="init_terminal" src="http://foad-images.simplon.co/s01/Initiation_shell_cygwin.mp4" type="video/mp4" controls></video>
```

Le site me retourne

```
The change you wanted was rejected.

Maybe you tried to change something you didn't have access to.
```

**Comment by yaf** [comment]
Je crois que pour le moment nous allons proposer les vidéos sous forme de lien. Je me demande si ce n'est pas un soucis de server de fichier, qui ne proposerais pas ce qu'il faut... Je vais regarder coté config nginx :-)

**Comment by yaf** [comment]
Bon, en local, ça fonctionne. Ce ne dois pas être ça alors...

**Comment by giniouxe** [comment]
Conflit avec CodeRay (coloration syntaxique) ? A vérifier.
